[display]
screen_size.x = 800
screen_size.y = 800
grid_size.x = 10
grid_size.y = 10

[game]
tps = 2

[apples]
number = 2
power = 1

[textures]
apples = "apple.png"
walls = "mud.png"
background = "grass.png"

[walls]
map = "smile.csv"

[keys]
pause = "SPACE"
exit = "ESCAPE"