SCREEN_SIZE_X = 800
SCREEN_SIZE_Y = 800
SNAKE_GRID_SIZE_X = 10
SNAKE_GRID_SIZE_Y = 10

TICK_PER_SECOND = 2
INITIAL_APPLES = 2
DEFAULT_APPLES_POWER = 1

FOOD_DEFAULT_TEXTURES = "default.png"
WALLS_DEFAULT_TEXTURES = "default.png"

BACKGROUND_COLOR = "#eeeeee"

WALLS_MAP = "smile.csv"

PAUSE_KEY = "SPACE"
EXIT_KEY = "ESCAPE"