[display]
screen_size.x = 900
screen_size.y = 900
grid_size.x = 20
grid_size.y = 20

[game]
tps = 3

[apples]
number = 3
power = 1

[textures]
apples = "apple.png"
walls = "mud.png"
background = "grass.png"

[walls]
map = "fountain10x10.csv"

[keys]
pause = "SPACE"
exit = "ESCAPE"