# Check the docs/config.md for informations on how to configure this file

[display]
screen_size.x = 900
screen_size.y = 900

[game]
tps = 2
grid_size.x = 15
grid_size.y = 15

[apples]
number = 3
power = 1
textures = "apple.png"

[walls]
map = "zen15x15.csv"
textures = "mud.png"

[background]
textures = "grass.png"

[keys]
pause = "SPACE"
exit = "ESCAPE"

[logs]
level="DEBUG"